/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc520TokenSol from "./erc520-token.sol";
export type { erc520TokenSol };
import type * as erc520Sol from "./erc520.sol";
export type { erc520Sol };
import type * as erc721EnumerableSol from "./erc721-enumerable.sol";
export type { erc721EnumerableSol };
import type * as erc721MetadataSol from "./erc721-metadata.sol";
export type { erc721MetadataSol };
import type * as erc721TokenReceiverSol from "./erc721-token-receiver.sol";
export type { erc721TokenReceiverSol };
import type * as erc721Sol from "./erc721.sol";
export type { erc721Sol };
import type * as nfTokenEnumerableSol from "./nf-token-enumerable.sol";
export type { nfTokenEnumerableSol };
import type * as nfTokenMetadataSol from "./nf-token-metadata.sol";
export type { nfTokenMetadataSol };
import type * as nfTokenSol from "./nf-token.sol";
export type { nfTokenSol };
