/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marry3TokenSol from "./marry3-token.sol";
export type { marry3TokenSol };
import type * as marry3Sol from "./marry3.sol";
export type { marry3Sol };
