/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SupportsInterface,
  SupportsInterfaceInterface,
} from "../../../../contracts/utils/supports-interface.sol/SupportsInterface";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_interfaceID",
        type: "bytes4",
      },
    ],
    name: "supportsInterface",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506301ffc9a760e01b60009081526020527f67be87c3ff9960ca1e9cfac5cab2ff4747269cf9ed20c9b7306235ac35a491c5805460ff191660011790556101008061005c6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806301ffc9a714602d575b600080fd5b606f60383660046083565b7fffffffff000000000000000000000000000000000000000000000000000000001660009081526020819052604090205460ff1690565b604051901515815260200160405180910390f35b600060208284031215609457600080fd5b81357fffffffff000000000000000000000000000000000000000000000000000000008116811460c357600080fd5b939250505056fea2646970667358221220596df56af2d8cbca19d6d806cb9ce49c009e2db7e3fdbcc4ac8ee2ac3b13b22064736f6c63430008090033";

type SupportsInterfaceConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SupportsInterfaceConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SupportsInterface__factory extends ContractFactory {
  constructor(...args: SupportsInterfaceConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SupportsInterface> {
    return super.deploy(overrides || {}) as Promise<SupportsInterface>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): SupportsInterface {
    return super.attach(address) as SupportsInterface;
  }
  override connect(signer: Signer): SupportsInterface__factory {
    return super.connect(signer) as SupportsInterface__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SupportsInterfaceInterface {
    return new utils.Interface(_abi) as SupportsInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SupportsInterface {
    return new Contract(address, _abi, signerOrProvider) as SupportsInterface;
  }
}
