/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc165Sol from "./erc165.sol";
export type { erc165Sol };
import type * as supportsInterfaceSol from "./supports-interface.sol";
export type { supportsInterfaceSol };
