/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as addressUtilsMockSol from "./address-utils-mock.sol";
export type { addressUtilsMockSol };
import type * as nfTokenEnumerableTestMockSol from "./nf-token-enumerable-test-mock.sol";
export type { nfTokenEnumerableTestMockSol };
import type * as nfTokenMetadataEnumerableTestMockSol from "./nf-token-metadata-enumerable-test-mock.sol";
export type { nfTokenMetadataEnumerableTestMockSol };
import type * as nfTokenMetadataTestMockSol from "./nf-token-metadata-test-mock.sol";
export type { nfTokenMetadataTestMockSol };
import type * as nfTokenReceiverTestMockSol from "./nf-token-receiver-test-mock.sol";
export type { nfTokenReceiverTestMockSol };
import type * as nfTokenTestMockSol from "./nf-token-test-mock.sol";
export type { nfTokenTestMockSol };
import type * as sendsToSelfOnConstructSol from "./sends-to-self-on-construct.sol";
export type { sendsToSelfOnConstructSol };
