/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nfTokenEnumerableMockSol from "./nf-token-enumerable-mock.sol";
export type { nfTokenEnumerableMockSol };
import type * as nfTokenMetadataBaseUriMockSol from "./nf-token-metadata-base-uri-mock.sol";
export type { nfTokenMetadataBaseUriMockSol };
import type * as nfTokenMetadataEnumerableMockSol from "./nf-token-metadata-enumerable-mock.sol";
export type { nfTokenMetadataEnumerableMockSol };
import type * as nfTokenMetadataMockSol from "./nf-token-metadata-mock.sol";
export type { nfTokenMetadataMockSol };
import type * as nfTokenMockSol from "./nf-token-mock.sol";
export type { nfTokenMockSol };
